version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: frimousse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: sh -c "npx prisma db push && npm run start:prod"
    volumes:
      - uploads_data:/usr/src/app/uploads
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PUBLIC_BASE_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/frimousse
      CLOUDINARY_CLOUD_NAME: dvyhnuq1r
      CLOUDINARY_API_KEY: 862842173635923
      CLOUDINARY_API_SECRET: XSUfAXh5Xon2fhllMlIzCnW8lL0
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

volumes:
  uploads_data:
  postgres_data:
