version: "3.8"
services:
  app:
    build: .
    command: npm run start:prod
    volumes:
      - uploads_data:/usr/src/app/uploads
      - db_data:/usr/src/app/prisma
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PUBLIC_BASE_URL: http://localhost:3000
      DATABASE_URL: file:./prisma/dev.db
    restart: unless-stopped

volumes:
  uploads_data:
  db_data:
